// GENERATED by design/generate.mjs from design/tokens/tokens.json. Do not edit.
package os.meka.android.designsystem

import androidx.compose.animation.core.Spring
import androidx.compose.animation.core.spring
import androidx.compose.animation.core.tween
import androidx.compose.animation.core.FiniteAnimationSpec
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp

data class MekaColors(
    val background: Color,
    val surface: Color,
    val surfaceRaised: Color,
    val hairline: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val accent: Color,
    val onAccent: Color,
    val critical: Color,
    val approval: Color,
    val offline: Color,
    val success: Color,
    val barca: Color,
)

val MekaDarkColors = MekaColors(
    background = Color(0xFF000000),
    surface = Color(0xFF0E0E10),
    surfaceRaised = Color(0xFF17171A),
    hairline = Color(0xFF26262B),
    textPrimary = Color(0xFFF4F4F5),
    textSecondary = Color(0xFFA1A1AA),
    textTertiary = Color(0xFF63636B),
    accent = Color(0xFFC9B37E),
    onAccent = Color(0xFF14120C),
    critical = Color(0xFFF2766B),
    approval = Color(0xFF8FB8F2),
    offline = Color(0xFFA1A1AA),
    success = Color(0xFF8CC9A0),
    barca = Color(0xFFE57A98),
)

val MekaLightColors = MekaColors(
    background = Color(0xFFFAFAF7),
    surface = Color(0xFFFFFFFF),
    surfaceRaised = Color(0xFFF2F1EC),
    hairline = Color(0xFFE4E2DA),
    textPrimary = Color(0xFF111113),
    textSecondary = Color(0xFF5B5B63),
    textTertiary = Color(0xFF7E7E86),
    accent = Color(0xFF8A6F2F),
    onAccent = Color(0xFFFFFFFF),
    critical = Color(0xFFB4372C),
    approval = Color(0xFF2F5FA8),
    offline = Color(0xFF5B5B63),
    success = Color(0xFF2E7D4F),
    barca = Color(0xFFA50044),
)

object MekaType {
    val greeting = TextStyle(fontSize = 34.sp, fontWeight = FontWeight(600), lineHeight = 39.1.sp, letterSpacing = -0.02.em)
    val sectionLabel = TextStyle(fontSize = 13.sp, fontWeight = FontWeight(600), lineHeight = 16.9.sp, letterSpacing = 0.08.em)
    val itemTitle = TextStyle(fontSize = 19.sp, fontWeight = FontWeight(500), lineHeight = 24.7.sp, letterSpacing = -0.005.em)
    val itemMeta = TextStyle(fontSize = 15.sp, fontWeight = FontWeight(400), lineHeight = 20.3.sp, letterSpacing = 0.em)
    val upNextTitle = TextStyle(fontSize = 26.sp, fontWeight = FontWeight(600), lineHeight = 31.2.sp, letterSpacing = -0.015.em)
    val body = TextStyle(fontSize = 17.sp, fontWeight = FontWeight(400), lineHeight = 24.6.sp, letterSpacing = 0.em)
    val caption = TextStyle(fontSize = 13.sp, fontWeight = FontWeight(400), lineHeight = 16.9.sp, letterSpacing = 0.01.em)
}

object MekaSpace {
    val xxs = 4.dp
    val xs = 8.dp
    val s = 12.dp
    val m = 16.dp
    val l = 24.dp
    val xl = 32.dp
    val xxl = 48.dp
    val gutter = 20.dp
}

object MekaRadius {
    val s = 10.dp
    val m = 16.dp
    val l = 24.dp
    val pill = 999.dp
}

/** Appearance → Motion (motion pass 2): Expressive uses the bouncier springs. Set by MekaTheme; read when a spec is made. */
object MotionStyle {
    @Volatile var expressive: Boolean = true
}

/** Semantic motion. Pass reducedMotion from the Motion setting; reduced = short tween, callers drop translation. */
object MekaMotion {
    fun <T> complete(reducedMotion: Boolean, expressive: Boolean = MotionStyle.expressive): FiniteAnimationSpec<T> =
        if (reducedMotion) tween(120) else spring(dampingRatio = if (expressive) 0.75f else 0.82f, stiffness = 420f)
    const val completeDurationMs = 280
    fun <T> replan(reducedMotion: Boolean): FiniteAnimationSpec<T> =
        if (reducedMotion) tween(140) else spring(dampingRatio = 0.9f, stiffness = 300f)
    const val replanDurationMs = 360
    fun <T> expand(reducedMotion: Boolean): FiniteAnimationSpec<T> =
        if (reducedMotion) tween(120) else spring(dampingRatio = 0.86f, stiffness = 380f)
    const val expandDurationMs = 300
    fun <T> approve(reducedMotion: Boolean, expressive: Boolean = MotionStyle.expressive): FiniteAnimationSpec<T> =
        if (reducedMotion) tween(100) else spring(dampingRatio = if (expressive) 0.62f else 0.7f, stiffness = 500f)
    const val approveDurationMs = 240
    fun <T> syncPulse(reducedMotion: Boolean): FiniteAnimationSpec<T> =
        if (reducedMotion) tween(0) else spring(dampingRatio = 1f, stiffness = 120f)
    const val syncPulseDurationMs = 900
    fun <T> appear(reducedMotion: Boolean): FiniteAnimationSpec<T> =
        if (reducedMotion) tween(120) else spring(dampingRatio = 0.9f, stiffness = 350f)
    const val appearDurationMs = 220
    fun <T> themeBlend(reducedMotion: Boolean): FiniteAnimationSpec<T> =
        if (reducedMotion) tween(0) else spring(dampingRatio = 1f, stiffness = 200f)
    const val themeBlendDurationMs = 450
}

/** Sequencing for motion (stagger, rise, count-up, shimmer). Values in ms unless the name says otherwise. */
object MekaChoreography {
    const val staggerStepMs = 40
    const val staggerMaxSteps = 8
    const val riseDistanceDp = 12
    const val countUpMs = 700
    const val shimmerPeriodMs = 1200
    const val expressiveStaggerStepMs = 60
    const val expressiveRiseDistanceDp = 28
    const val expressiveCountUpMs = 900
    const val expressiveEntryScale = 0.96f
    const val pressScale = 0.97f
    const val hoverLiftDp = 2
    const val pullThresholdDistanceDp = 64
    const val pullMaxDistanceDp = 112
    const val syncSpinPeriodMs = 900
    const val sheetScrimOpacity = 0.5f
    const val checkDrawMs = 420
    const val emptyBreathPeriodMs = 4200
}
