// GENERATED by design/generate.mjs from design/tokens/tokens.json. Do not edit.
import SwiftUI

struct MekaPalette {
    let background: Color
    let surface: Color
    let surfaceRaised: Color
    let hairline: Color
    let textPrimary: Color
    let textSecondary: Color
    let textTertiary: Color
    let accent: Color
    let onAccent: Color
    let critical: Color
    let approval: Color
    let offline: Color
    let success: Color
    let barca: Color
    let calendar1: Color
    let calendar2: Color
    let calendar3: Color
    let calendar4: Color
    let calendar5: Color
    let rain: Color
}

extension MekaPalette {
    static let dark = MekaPalette(
        background: Color(.sRGB, red: 0.0000, green: 0.0000, blue: 0.0000, opacity: 1),
        surface: Color(.sRGB, red: 0.0549, green: 0.0549, blue: 0.0627, opacity: 1),
        surfaceRaised: Color(.sRGB, red: 0.0902, green: 0.0902, blue: 0.1020, opacity: 1),
        hairline: Color(.sRGB, red: 0.1490, green: 0.1490, blue: 0.1686, opacity: 1),
        textPrimary: Color(.sRGB, red: 0.9569, green: 0.9569, blue: 0.9608, opacity: 1),
        textSecondary: Color(.sRGB, red: 0.6314, green: 0.6314, blue: 0.6667, opacity: 1),
        textTertiary: Color(.sRGB, red: 0.3882, green: 0.3882, blue: 0.4196, opacity: 1),
        accent: Color(.sRGB, red: 0.7882, green: 0.7020, blue: 0.4941, opacity: 1),
        onAccent: Color(.sRGB, red: 0.0784, green: 0.0706, blue: 0.0471, opacity: 1),
        critical: Color(.sRGB, red: 0.9490, green: 0.4627, blue: 0.4196, opacity: 1),
        approval: Color(.sRGB, red: 0.5608, green: 0.7216, blue: 0.9490, opacity: 1),
        offline: Color(.sRGB, red: 0.6314, green: 0.6314, blue: 0.6667, opacity: 1),
        success: Color(.sRGB, red: 0.5490, green: 0.7882, blue: 0.6275, opacity: 1),
        barca: Color(.sRGB, red: 0.8980, green: 0.4784, blue: 0.5961, opacity: 1),
        calendar1: Color(.sRGB, red: 0.3725, green: 0.7608, blue: 0.7216, opacity: 1),
        calendar2: Color(.sRGB, red: 0.7059, green: 0.6118, blue: 0.9490, opacity: 1),
        calendar3: Color(.sRGB, red: 0.9098, green: 0.6353, blue: 0.4157, opacity: 1),
        calendar4: Color(.sRGB, red: 0.4902, green: 0.7020, blue: 0.9098, opacity: 1),
        calendar5: Color(.sRGB, red: 0.7176, green: 0.7686, blue: 0.4157, opacity: 1),
        rain: Color(.sRGB, red: 0.4980, green: 0.6980, blue: 0.8980, opacity: 1)
    )
}

extension MekaPalette {
    static let light = MekaPalette(
        background: Color(.sRGB, red: 0.9804, green: 0.9804, blue: 0.9686, opacity: 1),
        surface: Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 1),
        surfaceRaised: Color(.sRGB, red: 0.9490, green: 0.9451, blue: 0.9255, opacity: 1),
        hairline: Color(.sRGB, red: 0.8941, green: 0.8863, blue: 0.8549, opacity: 1),
        textPrimary: Color(.sRGB, red: 0.0667, green: 0.0667, blue: 0.0745, opacity: 1),
        textSecondary: Color(.sRGB, red: 0.3569, green: 0.3569, blue: 0.3882, opacity: 1),
        textTertiary: Color(.sRGB, red: 0.4941, green: 0.4941, blue: 0.5255, opacity: 1),
        accent: Color(.sRGB, red: 0.5412, green: 0.4353, blue: 0.1843, opacity: 1),
        onAccent: Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 1),
        critical: Color(.sRGB, red: 0.7059, green: 0.2157, blue: 0.1725, opacity: 1),
        approval: Color(.sRGB, red: 0.1843, green: 0.3725, blue: 0.6588, opacity: 1),
        offline: Color(.sRGB, red: 0.3569, green: 0.3569, blue: 0.3882, opacity: 1),
        success: Color(.sRGB, red: 0.1804, green: 0.4902, blue: 0.3098, opacity: 1),
        barca: Color(.sRGB, red: 0.6471, green: 0.0000, blue: 0.2667, opacity: 1),
        calendar1: Color(.sRGB, red: 0.1216, green: 0.4784, blue: 0.4471, opacity: 1),
        calendar2: Color(.sRGB, red: 0.4157, green: 0.3098, blue: 0.7608, opacity: 1),
        calendar3: Color(.sRGB, red: 0.6510, green: 0.3529, blue: 0.1098, opacity: 1),
        calendar4: Color(.sRGB, red: 0.1765, green: 0.4353, blue: 0.6824, opacity: 1),
        calendar5: Color(.sRGB, red: 0.4000, green: 0.4392, blue: 0.1176, opacity: 1),
        rain: Color(.sRGB, red: 0.1843, green: 0.4235, blue: 0.6588, opacity: 1)
    )
}

enum MekaType {
    static let greeting = Font.system(size: 34, weight: .semibold)
    static let greetingTracking: CGFloat = -0.68
    static let sectionLabel = Font.system(size: 13, weight: .semibold)
    static let sectionLabelTracking: CGFloat = 1.04
    static let itemTitle = Font.system(size: 19, weight: .medium)
    static let itemTitleTracking: CGFloat = -0.10
    static let itemMeta = Font.system(size: 15, weight: .regular)
    static let itemMetaTracking: CGFloat = 0.00
    static let upNextTitle = Font.system(size: 26, weight: .semibold)
    static let upNextTitleTracking: CGFloat = -0.39
    static let nowTitle = Font.system(size: 22, weight: .semibold)
    static let nowTitleTracking: CGFloat = -0.22
    static let body = Font.system(size: 17, weight: .regular)
    static let bodyTracking: CGFloat = 0.00
    static let caption = Font.system(size: 13, weight: .regular)
    static let captionTracking: CGFloat = 0.13
}

enum MekaSpace {
    static let xxs: CGFloat = 4
    static let xs: CGFloat = 8
    static let s: CGFloat = 12
    static let m: CGFloat = 16
    static let l: CGFloat = 24
    static let xl: CGFloat = 32
    static let xxl: CGFloat = 48
    static let gutter: CGFloat = 16
    static let gutterWide: CGFloat = 24
    static let touch: CGFloat = 48
}

enum MekaRadius {
    static let s: CGFloat = 10
    static let m: CGFloat = 16
    static let l: CGFloat = 24
    static let pill: CGFloat = 999
}

/// Appearance → Motion (motion pass 2): Expressive uses the bouncier springs. Set on the main thread by the app
/// (MotionSetting.swift); read when an animation is made.
enum MotionStyle {
    nonisolated(unsafe) static var expressive = true
}

/// Semantic motion. Reduced = short ease, callers drop translation.
enum MekaMotion {
    static func complete(reduced: Bool, expressive: Bool = MotionStyle.expressive) -> Animation { reduced ? .easeOut(duration: 0.120) : .spring(response: 0.307, dampingFraction: expressive ? 0.75 : 0.82) }
    static func replan(reduced: Bool) -> Animation { reduced ? .easeOut(duration: 0.140) : .spring(response: 0.363, dampingFraction: 0.9) }
    static func expand(reduced: Bool) -> Animation { reduced ? .easeOut(duration: 0.120) : .spring(response: 0.322, dampingFraction: 0.86) }
    static func approve(reduced: Bool, expressive: Bool = MotionStyle.expressive) -> Animation { reduced ? .easeOut(duration: 0.100) : .spring(response: 0.281, dampingFraction: expressive ? 0.62 : 0.7) }
    static func syncPulse(reduced: Bool) -> Animation { reduced ? .easeOut(duration: 0.000) : .spring(response: 0.574, dampingFraction: 1) }
    static func appear(reduced: Bool, expressive: Bool = MotionStyle.expressive) -> Animation { reduced ? .easeOut(duration: 0.120) : .spring(response: expressive ? 0.468 : 0.336, dampingFraction: 0.9) }
    static func themeBlend(reduced: Bool) -> Animation { reduced ? .easeOut(duration: 0.000) : .spring(response: 0.444, dampingFraction: 1) }
}

/// Sequencing for motion (stagger, rise, count-up, shimmer). Durations in seconds; distances in points.
enum MekaChoreography {
    static let staggerStep: Double = 0.040
    static let staggerMaxSteps = 8
    static let riseDistance: CGFloat = 12
    static let countUp: Double = 0.700
    static let shimmerPeriod: Double = 1.200
    static let expressiveStaggerStep: Double = 0.060
    static let expressiveRiseDistance: CGFloat = 28
    static let expressiveCountUp: Double = 0.900
    static let expressiveEntryScale: CGFloat = 0.96
    static let pressScale: CGFloat = 0.97
    static let hoverLift: CGFloat = 2
    static let pullThresholdDistance: CGFloat = 64
    static let pullMaxDistance: CGFloat = 112
    static let syncSpinPeriod: Double = 0.900
    static let sheetScrimOpacity: CGFloat = 0.5
    static let checkDraw: Double = 0.420
    static let dayRingMark: Double = 0.600
    static let dayRingArc: Double = 0.360
    static let dayRingNeedle: Double = 0.720
    static let dayRingQuick: Double = 0.500
    static let expressiveDayRingQuick: Double = 0.900
    static let expressiveDayRingScale: CGFloat = 1.4
    static let greetingLetter: Double = 0.028
    static let greetingLetterFade: Double = 0.260
    static let emptyBreathPeriod: Double = 4.200
    static let swipeArmDistance: CGFloat = 96
    static let swipeIconPopScale: CGFloat = 1.25
    static let tabIconPopScale: CGFloat = 1.15
}
