#!/usr/bin/env node
// Generates platform token files from design/tokens/tokens.json (ADR-012). Dependency-free.
// Usage: node design/generate.mjs [--check]   (--check fails if committed outputs are stale; used in CI)
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const t = JSON.parse(readFileSync(join(root, 'design/tokens/tokens.json'), 'utf8'));
const check = process.argv.includes('--check');

const OUT = {
  kotlin: 'android/app/src/main/kotlin/os/meka/android/designsystem/MekaTokens.kt',
  swift: 'macos/MekaOS/DesignSystem/MekaTokens.swift',
};

const header = '// GENERATED by design/generate.mjs from design/tokens/tokens.json. Do not edit.\n';
const pascal = (s) => s[0].toUpperCase() + s.slice(1);
const entries = (o) => Object.entries(o).filter(([k]) => !k.startsWith('$'));

function hexToArgb(hex) {
  const h = hex.replace('#', '');
  if (!/^[0-9a-fA-F]{6}$/.test(h)) throw new Error(`bad colour ${hex}`);
  return `0xFF${h.toUpperCase()}`;
}
function hexToRgb(hex) {
  const h = hex.replace('#', '');
  return [0, 2, 4].map((i) => (parseInt(h.slice(i, i + 2), 16) / 255).toFixed(4));
}

// Validate both palettes define identical roles.
const darkRoles = entries(t.color.dark).map(([k]) => k).sort().join();
const lightRoles = entries(t.color.light).map(([k]) => k).sort().join();
if (darkRoles !== lightRoles) throw new Error('dark and light palettes must define the same roles');

// Accessibility gate (WCAG 2.2): body text roles >= 4.5:1, accent/state colours >= 3:1, on background and surface.
function luminance(hex) {
  const c = hexToRgb(hex).map(Number).map((v) => (v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4));
  return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
}
function contrast(a, b) {
  const [l1, l2] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (l1 + 0.05) / (l2 + 0.05);
}
const contrastRules = { textPrimary: 4.5, textSecondary: 4.5, textTertiary: 3, accent: 3, critical: 3, approval: 3, success: 3, barca: 3 };
const failures = [];
for (const mode of ['dark', 'light']) {
  for (const bg of ['background', 'surface', 'surfaceRaised']) {
    for (const [role, min] of Object.entries(contrastRules)) {
      const r = contrast(t.color[mode][role].$value, t.color[mode][bg].$value);
      if (r < min) failures.push(`${mode}.${role} on ${bg}: ${r.toFixed(2)} < ${min}`);
    }
  }
}
if (failures.length) { console.error('Contrast failures:\n' + failures.join('\n')); process.exit(1); }

function kotlin() {
  let s = header + 'package os.meka.android.designsystem\n\n';
  s += 'import androidx.compose.animation.core.Spring\nimport androidx.compose.animation.core.spring\nimport androidx.compose.animation.core.tween\nimport androidx.compose.animation.core.FiniteAnimationSpec\n';
  s += 'import androidx.compose.ui.graphics.Color\nimport androidx.compose.ui.text.TextStyle\nimport androidx.compose.ui.text.font.FontWeight\nimport androidx.compose.ui.unit.dp\nimport androidx.compose.ui.unit.em\nimport androidx.compose.ui.unit.sp\n\n';
  s += 'data class MekaColors(\n' + entries(t.color.dark).map(([k]) => `    val ${k}: Color,`).join('\n') + '\n)\n\n';
  for (const mode of ['dark', 'light']) {
    s += `val Meka${pascal(mode)}Colors = MekaColors(\n` + entries(t.color[mode]).map(([k, v]) => `    ${k} = Color(${hexToArgb(v.$value)}),`).join('\n') + '\n)\n\n';
  }
  s += 'object MekaType {\n';
  for (const [k, v] of entries(t.type)) {
    s += `    val ${k} = TextStyle(fontSize = ${v.size}.sp, fontWeight = FontWeight(${v.weight}), lineHeight = ${(v.size * v.lineHeight).toFixed(1)}.sp, letterSpacing = ${v.tracking}.em)\n`;
  }
  s += '}\n\nobject MekaSpace {\n' + entries(t.space).map(([k, v]) => `    val ${k} = ${v.$value}.dp`).join('\n') + '\n}\n\n';
  s += 'object MekaRadius {\n' + entries(t.radius).map(([k, v]) => `    val ${k} = ${v.$value}.dp`).join('\n') + '\n}\n\n';
  s += '/** Semantic motion. Pass reducedMotion from the system setting; reduced = short tween, callers drop translation. */\nobject MekaMotion {\n';
  for (const [k, v] of entries(t.motion)) {
    s += `    fun <T> ${k}(reducedMotion: Boolean): FiniteAnimationSpec<T> =\n        if (reducedMotion) tween(${v.reducedDuration}) else spring(dampingRatio = ${v.spring.damping}f, stiffness = ${v.spring.stiffness}f)\n`;
    s += `    const val ${k}DurationMs = ${v.duration}\n`;
  }
  s += '}\n';
  s += '\n/** Sequencing for motion (stagger, rise, count-up, shimmer). Values in ms unless the name says otherwise. */\nobject MekaChoreography {\n';
  for (const [k, v] of entries(t.choreography)) s += `    const val ${k}${k === 'staggerMaxSteps' ? '' : k === 'riseDistance' ? 'Dp' : 'Ms'} = ${v.$value}\n`;
  s += '}\n';
  return s;
}

function swift() {
  let s = header + 'import SwiftUI\n\n';
  s += 'struct MekaPalette {\n' + entries(t.color.dark).map(([k]) => `    let ${k}: Color`).join('\n') + '\n}\n\n';
  for (const mode of ['dark', 'light']) {
    s += `extension MekaPalette {\n    static let ${mode} = MekaPalette(\n` + entries(t.color[mode]).map(([k, v]) => {
      const [r, g, b] = hexToRgb(v.$value);
      return `        ${k}: Color(.sRGB, red: ${r}, green: ${g}, blue: ${b}, opacity: 1)`;
    }).join(',\n') + '\n    )\n}\n\n';
  }
  const weight = (w) => ({ 100: '.ultraLight', 200: '.thin', 300: '.light', 400: '.regular', 500: '.medium', 600: '.semibold', 700: '.bold', 800: '.heavy', 900: '.black' })[w];
  s += 'enum MekaType {\n';
  for (const [k, v] of entries(t.type)) {
    s += `    static let ${k} = Font.system(size: ${v.size}, weight: ${weight(v.weight)})\n    static let ${k}Tracking: CGFloat = ${(v.tracking * v.size).toFixed(2)}\n`;
  }
  s += '}\n\nenum MekaSpace {\n' + entries(t.space).map(([k, v]) => `    static let ${k}: CGFloat = ${v.$value}`).join('\n') + '\n}\n\n';
  s += 'enum MekaRadius {\n' + entries(t.radius).map(([k, v]) => `    static let ${k}: CGFloat = ${v.$value}`).join('\n') + '\n}\n\n';
  s += '/// Semantic motion. Reduced = short ease, callers drop translation.\nenum MekaMotion {\n';
  for (const [k, v] of entries(t.motion)) {
    // SwiftUI spring(response:dampingFraction:): response ≈ 2π/sqrt(stiffness) for unit mass.
    const response = (2 * Math.PI / Math.sqrt(v.spring.stiffness)).toFixed(3);
    s += `    static func ${k}(reduced: Bool) -> Animation { reduced ? .easeOut(duration: ${(v.reducedDuration / 1000).toFixed(3)}) : .spring(response: ${response}, dampingFraction: ${v.spring.damping}) }\n`;
  }
  s += '}\n';
  s += '\n/// Sequencing for motion (stagger, rise, count-up, shimmer). Durations in seconds; distances in points.\nenum MekaChoreography {\n';
  for (const [k, v] of entries(t.choreography)) {
    if (k === 'staggerMaxSteps') s += `    static let ${k} = ${v.$value}\n`;
    else if (k === 'riseDistance') s += `    static let ${k}: CGFloat = ${v.$value}\n`;
    else s += `    static let ${k}: Double = ${(v.$value / 1000).toFixed(3)}\n`;
  }
  s += '}\n';
  return s;
}

let stale = false;
for (const [lang, rel] of Object.entries(OUT)) {
  const content = lang === 'kotlin' ? kotlin() : swift();
  const path = join(root, rel);
  if (check) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) { console.error(`stale: ${rel}`); stale = true; }
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(`wrote ${rel}`);
  }
}
if (stale) { console.error('Run: node design/generate.mjs'); process.exit(1); }
