#!/usr/bin/env python3
"""MEKA's app icon: the gold watch face on black (build plan, call assistant polish item 9).

One geometry, two outputs, so the Fold and the Mac wear the same face:
  * the Fold's adaptive icon (vector drawables: foreground, monochrome, background) in android/app/src/main/res,
    and the same for the Galaxy Watch in wear/app/src/main/res
  * the Mac's AppIcon.appiconset (PNGs at every size macOS asks for) in macos/MekaOS/Assets.xcassets

The face is the watch face Today's header draws (WatchFace.kt): a brass rim, twelve markers with no numerals
(12 · 3 · 6 · 9 heavier), tapered hour and minute hands at 10:08 and a fine second hand. Colours are the design
tokens' dark theme: accent #C9B37E on true black.

Run from the repo root: python3 tools/make-app-icon.py   (needs Pillow; the outputs are committed)
"""
import json
import math
import os

BRASS = "#C9B37E"
BRASS_RGB = (0xC9, 0xB3, 0x7E)

# Face units: centre (0, 0), y down, angles clockwise from 12 o'clock.
RIM_R = 26.0
RIM_W = 3.0
MAJOR_FROM, MAJOR_TO, MAJOR_W = 17.6, 21.6, 2.4
MINOR_R, MINOR_DOT = 19.8, 1.05
HOUR = dict(deg=(10 + 8 / 60) * 30, length=11.5, tail=2.5, base=3.6, tip=1.7)
MINUTE = dict(deg=8 * 6, length=16.8, tail=2.5, base=2.8, tip=1.1)
SECOND = dict(deg=203, length=18.5, tail=5.0, width=0.8)
PIN_R = 2.7


def at(deg, r):
    a = math.radians(deg)
    return (r * math.sin(a), -r * math.cos(a))


def hand_polygon(h):
    """A tapered hand: wide at the pin, narrow at the tip, a short tail behind the pin."""
    a = math.radians(h["deg"])
    d = (math.sin(a), -math.cos(a))
    n = (math.cos(a), math.sin(a))
    def p(along, half):
        return (d[0] * along + n[0] * half, d[1] * along + n[1] * half)
    return [p(-h["tail"], h["base"] / 2), p(h["length"], h["tip"] / 2),
            p(h["length"], -h["tip"] / 2), p(-h["tail"], -h["base"] / 2)]


def majors():
    return [(at(d, MAJOR_FROM), at(d, MAJOR_TO)) for d in (0, 90, 180, 270)]


def minors():
    return [at(d, MINOR_R) for d in range(30, 360, 30) if d % 90]


def second_line():
    s = SECOND
    return (at(s["deg"] + 180, s["tail"]), at(s["deg"], s["length"]))


# ---- Android: 108 dp adaptive icon, face centred (the 66 dp safe zone holds the rim: 2 × 27.5 = 55 dp).

def f(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def circle_path(cx, cy, r):
    return (f"M{f(cx - r)},{f(cy)}a{f(r)},{f(r)} 0,1 1,{f(2 * r)},0"
            f"a{f(r)},{f(r)} 0,1 1,{f(-2 * r)},0Z")


def android_foreground(colour):
    c = 54.0
    t = lambda pt: (c + pt[0], c + pt[1])
    paths = []
    paths.append(f'    <path android:strokeColor="{colour}" android:strokeWidth="{f(RIM_W)}" '
                 f'android:pathData="{circle_path(c, c, RIM_R)}" />')
    major_d = "".join(f"M{f(t(a)[0])},{f(t(a)[1])}L{f(t(b)[0])},{f(t(b)[1])}" for a, b in majors())
    paths.append(f'    <path android:strokeColor="{colour}" android:strokeWidth="{f(MAJOR_W)}" '
                 f'android:strokeLineCap="round" android:pathData="{major_d}" />')
    minor_d = "".join(circle_path(*t(m), MINOR_DOT) for m in minors())
    paths.append(f'    <path android:fillColor="{colour}" android:pathData="{minor_d}" />')
    a, b = second_line()
    paths.append(f'    <path android:strokeColor="{colour}" android:strokeWidth="{f(SECOND["width"])}" '
                 f'android:strokeLineCap="round" android:strokeAlpha="0.8" '
                 f'android:pathData="M{f(t(a)[0])},{f(t(a)[1])}L{f(t(b)[0])},{f(t(b)[1])}" />')
    for h in (HOUR, MINUTE):
        pts = [t(p) for p in hand_polygon(h)]
        d = "M" + "L".join(f"{f(x)},{f(y)}" for x, y in pts) + "Z"
        paths.append(f'    <path android:fillColor="{colour}" android:pathData="{d}" />')
    paths.append(f'    <path android:fillColor="{colour}" android:pathData="{circle_path(c, c, PIN_R)}" />')
    return ("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
            "<!-- Generated by tools/make-app-icon.py: MEKA's watch face. Edit the script, not this file. -->\n"
            "<vector xmlns:android=\"http://schemas.android.com/apk/res/android\"\n"
            "    android:width=\"108dp\" android:height=\"108dp\" android:viewportWidth=\"108\" "
            "android:viewportHeight=\"108\">\n" + "\n".join(paths) + "\n</vector>\n")


ANDROID_BACKGROUND = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/make-app-icon.py: black with a faint warm glow behind the face. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient android:type="radial" android:centerX="54" android:centerY="54" android:gradientRadius="62"
                android:startColor="#1C1A14" android:endColor="#000000" />
        </aapt:attr>
    </path>
</vector>
"""

ANDROID_ADAPTIVE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/make-app-icon.py. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
"""


# ---- Mac: a 1024 px squircle (Apple's template: an 824 px body inset 100 px), face radius 300 px.

def mac_icon(size_px=1024, ss=4):
    from PIL import Image, ImageDraw
    S = size_px * ss
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    k = S / 1024
    body = (100 * k, 100 * k, 924 * k, 924 * k)
    # Body: black with a faint warm centre (a radial blend drawn as rings).
    mask = Image.new("L", (S, S), 0)
    ImageDraw.Draw(mask).rounded_rectangle(body, radius=185.4 * k, fill=255)
    bg = Image.new("RGBA", (S, S), (0, 0, 0, 255))
    g = ImageDraw.Draw(bg)
    steps = 64
    for i in range(steps, 0, -1):
        r = 520 * k * i / steps
        mix = (1 - i / steps) ** 1.6
        col = tuple(int(c * mix) for c in (0x1C, 0x1A, 0x14))
        g.ellipse((S / 2 - r, S / 2 - r, S / 2 + r, S / 2 + r), fill=col + (255,))
    img.paste(bg, (0, 0), mask)
    # Hairline edge so the black body reads on a dark Dock.
    ImageDraw.Draw(img).rounded_rectangle(body, radius=185.4 * k, outline=(0x26, 0x26, 0x2B, 255),
                                          width=max(1, int(3 * k)))
    d = ImageDraw.Draw(img)
    u = 300 * k / RIM_R
    cx = cy = S / 2
    t = lambda pt: (cx + pt[0] * u, cy + pt[1] * u)
    brass = BRASS_RGB + (255,)

    def disc(p, r, col=brass):
        d.ellipse((p[0] - r, p[1] - r, p[0] + r, p[1] + r), fill=col)

    def round_line(a, b, w, col=brass):
        d.line([a, b], fill=col, width=int(round(w)))
        disc(a, w / 2, col)
        disc(b, w / 2, col)

    r_out, r_in = (RIM_R + RIM_W / 2) * u, (RIM_R - RIM_W / 2) * u
    d.ellipse((cx - r_out, cy - r_out, cx + r_out, cy + r_out), fill=brass)
    hole = Image.new("L", (S, S), 0)
    ImageDraw.Draw(hole).ellipse((cx - r_in, cy - r_in, cx + r_in, cy + r_in), fill=255)
    img.paste(bg, (0, 0), hole)
    d = ImageDraw.Draw(img)
    for a, b in majors():
        round_line(t(a), t(b), MAJOR_W * u)
    for m in minors():
        disc(t(m), MINOR_DOT * u)
    a, b = second_line()
    round_line(t(a), t(b), SECOND["width"] * u, BRASS_RGB + (205,))
    for h in (HOUR, MINUTE):
        d.polygon([t(p) for p in hand_polygon(h)], fill=brass)
    disc((cx, cy), PIN_R * u)
    return img.resize((size_px, size_px), Image.LANCZOS)


MAC_SIZES = [(16, 1), (16, 2), (32, 1), (32, 2), (128, 1), (128, 2), (256, 1), (256, 2), (512, 1), (512, 2)]


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    files = {
        "drawable/ic_launcher_foreground.xml": android_foreground(BRASS),
        # Themed icons: the launcher tints this one shape, so it's the same face in a single colour.
        "drawable/ic_launcher_monochrome.xml": android_foreground("#FFFFFFFF"),
        "drawable/ic_launcher_background.xml": ANDROID_BACKGROUND,
        "mipmap-anydpi/ic_launcher.xml": ANDROID_ADAPTIVE,
        "mipmap-anydpi/ic_launcher_round.xml": ANDROID_ADAPTIVE,
    }
    # The phone and the Galaxy Watch (Galaxy Watch, slice 2) carry the same face.
    for app in ("android/app", "wear/app"):
        res = os.path.join(root, app, "src/main/res")
        for sub in ("drawable", "mipmap-anydpi"):
            os.makedirs(os.path.join(res, sub), exist_ok=True)
        for rel, text in files.items():
            with open(os.path.join(res, rel), "w") as fh:
                fh.write(text)

    iconset = os.path.join(root, "macos/MekaOS/Assets.xcassets/AppIcon.appiconset")
    os.makedirs(iconset, exist_ok=True)
    with open(os.path.join(root, "macos/MekaOS/Assets.xcassets/Contents.json"), "w") as fh:
        json.dump({"info": {"author": "xcode", "version": 1}}, fh, indent=2)
        fh.write("\n")
    master = mac_icon(1024)
    images = []
    for pt, scale in MAC_SIZES:
        px = pt * scale
        name = f"icon_{pt}x{pt}{'@2x' if scale == 2 else ''}.png"
        from PIL import Image
        (master if px == 1024 else master.resize((px, px), Image.LANCZOS)).save(
            os.path.join(iconset, name), optimize=True)
        images.append({"filename": name, "idiom": "mac", "scale": f"{scale}x", "size": f"{pt}x{pt}"})
    with open(os.path.join(iconset, "Contents.json"), "w") as fh:
        json.dump({"images": images, "info": {"author": "xcode", "version": 1}}, fh, indent=2)
        fh.write("\n")


if __name__ == "__main__":
    main()
